### ISSUE TITLE
Tests fail -   The variable ASDF/INTERFACE::*DEFINED-SYSTEMS* is unbound.

### ISSUE THREAD

**Issue by AndreasDavour** [naryl/cl-tui#9]
[ante@powerpad cl-tui]$ cat test-run.sh 
#!/bin/sh
sbcl --eval "(ql:quickload 'cl-tui)" --eval "(cl-tui:init-screen)" --eval "(loop while cl-tui::*running* do (sleep 1) finally (sb-ext:exit))"
[ante@powerpad cl-tui]$ ./test-run.sh 
This is SBCL 2.0.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "cl-tui":
  Load 1 ASDF system:
    cl-tui
; Loading "cl-tui"
.........
debugger invoked on a UNBOUND-VARIABLE in thread
#<THREAD "main thread" RUNNING {10005684C3}>:
  The variable ASDF/INTERFACE::*DEFINED-SYSTEMS* is unbound.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Retry using ASDF/INTERFACE::*DEFINED-SYSTEMS*.
  1: [USE-VALUE                    ] Use specified value.
  2: [STORE-VALUE                  ] Set specified value and use it.
  3: [RETRY                        ] Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the
                                     configuration.
  7: [ABORT                        ] Give up on "cl-tui"
  8:                                 Ignore runtime option --eval "(ql:quickload 'cl-tui)".
  9:                                 Skip rest of --eval and --load options.
 10:                                 Skip to toplevel READ/EVAL/PRINT loop.
 11: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(ASDF/INTERFACE:MAP-SYSTEM-CONNECTIONS #<FUNCTION (LAMBDA (ASDF/INTERFACE::CONNECTION) :IN ASDF/INTERFACE::LOAD-CONNECTED-SYSTEMS) {52BFEC1B}>)
   source: (MAPHASH
            (LAMBDA (K V)
              (DECLARE (IGNORE K))
              (WHEN (TYPEP (CDR V) 'SYSTEM-CONNECTION) (FUNCALL FN (CDR V))))
            *DEFINED-SYSTEMS*)
0] 11
[ante@powerpad cl-tui]$ ls
cl-tui.asd  COPYING  examples/  README.md  src/  test-run.sh*  TODO.wiki
[ante@powerpad cl-tui]$ git branch
* master
[ante@powerpad cl-tui]$

**Comment by naryl** [comment]
Can you show the backtrace too? I don't see how this error could originate in cl-tui code.
Also, test-run.sh doesn't run tests. It runs a simple script just to confirm that it can find usable curses implementation.

**Comment by AndreasDavour** [comment]
I tried to run that step by step by hand, and got another error. I know next to nothing about curses (I had the idea cl-tui would be where I started to learn...), so the messages mean very little to me. If that first message was something about missing a library or curses package, then the error was truly terrible. Maybe something underlying presenting very little information?

Anyway. This is how it looks like when I just try the first step of the script. To me it looks like something that stem from cl-charms, but that I can quickload without problem when I do it on its own. Does this makes sense to you?

$ sbcl --eval "(ql:quickload 'cl-tui)"
This is SBCL 1.5.7.58-381c5d06a, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "cl-tui":
  Load 1 ASDF system:
    cl-tui
; Loading "cl-tui"
........; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "MVWCHGAT" not found in the CL-CHARMS/LOW-LEVEL package.
;   
;       Line: 212, Column: 36, File-Position: 7399
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/ante/quicklisp/local-projects/cl-tui/src/frames.lisp" {100299F893}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {10005604C3}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-tui" "frames">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "cl-tui" "frames">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "cl-tui" "frames">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "cl-tui"
  7: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload 'cl-tui)".
  8:                                 Skip rest of --eval and --load options.
  9:                                 Skip to toplevel READ/EVAL/PRINT loop.
 10: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-tui" "frames">)))
   source: (ERROR 'COMPILE-FILE-ERROR :CONTEXT-FORMAT CONTEXT-FORMAT
                  :CONTEXT-ARGUMENTS CONTEXT-ARGUMENTS)
0] 10

**Comment by naryl** [comment]
> I know next to nothing about curses (I had the idea cl-tui would be where I started to learn...)

If you want to learn curses, then you should either look at `cl-charms` or just directly C curses tutorials. `cl-tui` is supposed to be a complete abstraction that keeps you away from interacting with curses directly.

That error message means that `cl-charms` is missing a binding to some obscure function I use. I sent them a PR months ago and I'm pretty sure it got accepted promptly. Try updating your cl-charms. To do it with quicklisp:
```lisp
(ql:update-client) ;; Actually update quicklisp itself
(ql:update-all-dists) ;; Update all quicklisp distributions and reinstall software you have from them
```

**Comment by AndreasDavour** [comment]
Thanks for the suggestions! I've tried to stay away from the C curses tutorials, as they degenerate into incomprehensible C syntax with pointers and other nonsense. I might take a look at cl-charms, though.

I thought I was up to date with all packages, but I had missed there was a new quicklisp client out, and after updating it all compiled fine. Thanks!
